# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
