# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0006_auto_20170422_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='destination',
            field=models.CharField(choices=[('ANGOLA', 'Angola'), ('GUINEA', 'Guinea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='origin',
            field=models.CharField(choices=[('ANGOLA', 'Angola'), ('GUINEA', 'Guinea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='purpose',
            field=models.CharField(choices=[('CASH', 'Cash'), ('PHONE CREDIT', 'Phone Credit')], max_length=50),
        ),
    ]
